#! /bin/sh

#==================================================
#
# GIT
# ~/.config/git/gitalias
#
#==================================================

# _________________________________________ LOCAL<|

#@ Ensure git is installed
type git >/dev/null 2>&1 || return

# ________________________________________ EXPORT<|

GIT_CONFIG_GLOBAL="$GDOTDIR/global/config"

# __________________________________________ EXEC<|

#@ Load Contextual Environment Variables
. "$DOTS_ENV_CTX/vcs"