#!/bin/sh

unalias \
	la \
	ll \
	lt \
	ltl \
	>/dev/null 2>&1

la() {
	eza \
		--almost-all \
		--icons \
		--hyperlink \
		--group-directories-first \
		--smart-group \
		--git \
		--time-style relative \
		"$@"
}
ll() { la --long "$@"; }
lt() { la --tree --no-user --git-ignore "$@"; }
ltl() { lt --long "$@"; }
