#!/bin/sh
# shellcheck disable=2153

command_exists() {
	command -v "$1" > /dev/null 2>&1
}

set_cmd() {
	while [ "$#" -ge 1 ]; do
		if command_exists "$1"; then
			printf "%s" "$1"
			return 0
		else
			shift
		fi
	done
}

set_cmd "$@" || return 1
