#!/bin/sh

#/> Info                                            <\
_APP="alacritty"
_NAME="Alacritty"
_DESC="a GPU-accelerated terminal emulator written in Rust"
_TYPE="tty"
_HOME="${DOTS_APP}/${_APP}"

#/> Config                                          <\
_EXT="yml"
_CFG="${_HOME}/${_APP}.${_EXT}"

#/> CMD                                             <\
_CMD="alacritty"
[ -f "$_CFG" ] && _CMD="${_CMD} --config-file ${_CFG}"

#/> LINK                                            <\
src="$_HOME"
