#!/bin/sh

#/> Info                                            <\
_APP="lsd"
_NAME="LSDeluxe"
_DESC="The next gen ls command "
_TYPE="tty"
_HOME="${DOTS_APP}/${_APP}"

#/> Config                                          <\
_CFG="config.yaml"
_CFG="${_HOME}/${_CFG}"

#/> CMD                                             <\
_CMD="lsd"
[ -f "$_CFG" ] && _CMD="${_CMD} --config ${_CFG}"

#/> LINK                                            <\
src="$_HOME"
