#!/bin/sh

establish_environment() {
  #@ Set environment context file
  if [ "$WAYLAND_DISPLAY" ]; then
    env="${DOTS_ENV_CTX}/wayland"
  else
    case "$DISPLAY" in *:*)
      env="${DOTS_ENV_CTX}/X11"
      ;;
    esac
  fi
}

execute() {
  #@ Load Environment Variables from file
  if [ -f "$env" ]; then
    . "$env"
  else
    printf "Missing environment file: %s\n" "$env"
    exit 1
  fi
}

main() {
  execute
} && main "$@"
