#!/bin/sh

label="Display"

main() {
  execute
}

execute() {
  if [ "$WAYLAND_DISPLAY" ]; then
    . "${DOTS_ENV_CTX}/wayland"
  else
    case "$DISPLAY" in
    *:*) . "${DOTS_ENV_CTX}/X11" ;;
    esac
  fi
}

main
