#!/bin/sh

#TODO: This doesn't work because the $SHELL is always bash
case "$SHELL" in
*ash) . "$RC_bash" ;;
*zsh) . "$RC_zsh" ;;
*fish) . "$RC_fish" ;;
*nu) . "$RC_nush" ;;
esac

if type sysInfo >/dev/null 2>&1; then
  sysInfo
else
  exit
fi