#!/bin/sh

#> NAME
_APP="bash"
_NAME="bash"
_CMD="bash"
_TYPE="tty"

DOTS_CLI="${DOTS_CLI:-$DOTS/Configuration/cli}"
_HOME="${DOTS_CLI}/${_APP}"
_CONF="${DOTS_CLI}/${_APP}/config"
BDOTDIR="$_HOME"

[ -f "$_CONF" ] && . "$_CONF"

# for resource in "${_HOME}"/resources/*.*; do
#   [ -f "$resource" ] && . "$resource"
# done

# for function in "${_HOME}/"functions/*.*; do
#   [ -r "$function" ] && . "$function"
# done

# find "${_HOME}" -type f -exec . {} + 2>/dev/null

unset _HOME resource function
