#!/bin/sh

#> NAME
_APP="bash"
_NAME="bash"
_CMD="bash"
_TYPE="tty"

DOTS_CLI="${DOTS_CLI:-$DOTS/Config/cli}"
_HOME="${DOTS_CLI}/${_APP}"

for resource in "${_HOME}"/resources/*.*; do
  if [ -r "$resource" ]; then
    . "$resource"
  fi
done

for function in "${_HOME}/"functions/*.*; do
  if [ -r "$function" ]; then
    . "$function"
  fi
done

unset _HOME resource function
