#!/bin/sh

#> NAME
_APP="bat"
_NAME="bat"
_CMD="bat"

#> Config
_HOME="${DOTS_CLI}/${_APP}"
_EXT="config"
_CFG="${_HOME}/${_APP}.${_EXT}"
BAT_CONFIG_PATH="$_CFG"

#> CMD
weHave "$_CMD" || {
  eko ':x: $_NAME not found.'
  _ERR=true
  exit 1
}

[ -f "$_CFG" ] && {
  export BAT_CONFIG_PATH
  _CMD="${_CMD}"
}

#> TYPE
_TYPE="tty"
