#!/bin/sh

#> INFO
_APP="bat"
_NAME="bat"
_CMD="bat"
_TYPE="tty"

#> Config
DOTS_CLI="${DOTS_CLI:-$DOTS/Config/cli}"
_HOME="${DOTS_CLI}/${_APP}"
_EXT="config"
_CFG="${_HOME}/${_APP}.${_EXT}"
BAT_CONFIG_PATH="$_CFG"

#> CMD
weHave "$_CMD" || {
  eko ':x: $_NAME not found.'
  _ERR=true
  exit 1
}

[ -f "$_CFG" ] && {
  export BAT_CONFIG_PATH
  _CMD="${_CMD $*}"
}
