#!/bin/sh

FONTS_HOME="${DOTS_RES}/Fonts"
FONT_CONFIG_HOME="$FONTS_HOME/config"
FONT_TYPES_HOME="$FONTS_HOME/types"
FONTCONFIG_USER="$CONFIG_HOME/fontconfig"
LOCAL_SHARE="$HOME/.local/share"

#| Link
FONT_CONFIG_LINK="$FONTCONFIG_USER/conf.d"
FONT_TYPES_LINK="$LOCAL_SHARE/fonts"

#| Ensure Fontconfig Directory exists
mkdir --parents --verbose "$FONTCONFIG_USER"
mkdir --parents --verbose "$LOCAL_SHARE"

#| Deploy Link
symbiolink \
  --src "$FONT_CONFIG_HOME" \
  --lnk "$FONT_CONFIG_LINK"
symbiolink \
  --src "$FONT_TYPES_HOME" \
  --lnk "$FONT_TYPES_LINK"