#!/bin/sh

#/> Info                                            <\
_APP="git"
_NAME="git"
_DESC=""
_TYPE="tty"
_HOME="${DOTS_CLI}/${_APP}"

#/> Config                                          <\
_EXT="conf"
_CFG="${_HOME}/${_APP}.${_EXT}"

#/> CMD                                             <\
_CMD="git"
[ -f "$_CFG" ] && _CMD="${_CMD} --config ${_CFG}"

#/> LINK                                            <\
src="$_HOME"
