#!/bin/sh

#/> Info                                            <\
_APP="kitty"
_NAME="Kitty Terminal"
_DESC="a fast feature-rich ,GPU based terminal emulator"
_TYPE="tty"
_HOME="${DOTS_APP}/${_APP}"

#/> Config                                          <\
_EXT="conf"
_CFG="${_HOME}/${_APP}.${_EXT}"

#/> CMD                                             <\
_CMD="kitty"
[ -f "$_CFG" ] && _CMD="${_CMD} --config ${_CFG}"

#/> LINK                                            <\
src="$_HOME"
