#!/bin/sh

#> Info
_APP="vscode"
_NAME="Visual Studio Code"

#> Type of Application
_TYPE="gui"

#| Config
_HOME="${DOTS_APP}/${_APP}"
_CFG="${_HOME}/settings.json"

#> Command
if weHave code-insiders; then
  _CMD="code-insiders"
elif weHave code; then
  _CMD="code"
elif weHave code-oss; then
  _CMD="code-oss"
elif Flatpak_check visualstudio.code; then
  _CMD="$(Flatpak_run visualstudio.code)"
fi

[ "$_CMD" ] || {
  printf "🟥 %s not found." "$_NAME"
  exit 1
}
