#!/bin/sh

#> Info
_APP="vscode"
_NAME="Visual Studio Code"

#> TYPE
_TYPE="gui"

#> CMD
if weHave code-insiders; then
  _CMD="code-insiders"
elif weHave code; then
  _CMD="code"
elif weHave code-oss; then
  _CMD="code-oss"
elif Flatpak_check visualstudio.code; then
  _CMD="$(Flatpak_run visualstudio.code)"
fi

[ "$_CMD" ] || {
  eko ':x: $_NAME not found.'
  exit 1
}
