#!/bin/sh
app="wezterm"

# | Parse options
while [ $# -gt 0 ]; do
	case $1 in
	-h | --help)
		echo "Usage: Launch the default terminal emulator"
		exit 0
		;;
	--default | -app) app="$2" ;;
	*)
		echo "Unknown option: $1"
		exit 1
		;;
	esac
done

# | Set the terminal class
case "$app" in
wezterm) app_id="org.wezfurlong.wezterm" ;;
alacritty) app_id="Alacritty" ;;
kitty) app_id="kitty" ;;
rio) app_id="rio" ;;
st) app_id="st" ;;
terminator) app_id="Terminator" ;;
xfce4-terminal) app_id="Xfce4-terminal" ;;
*)
	echo "Unknown terminal emulator: $app"
	exit 1
	;;
esac

# | Launch the terminal emulator
# Use wmctrl to check if wezterm window is already running
if wmctrl -l -x | grep "$app_id" >/dev/null; then
	#> Activate the window
	wmctrl -x -a "$app_id"
else
	#>  Start the application
	$app &
fi
