# ~/.config/starship.toml

# Use custom format
format = '$all'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 800

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'
