#!/bin/bash

# Purpose: This script initializes BDOTDIR and loads bash resources and functions.

# Get the directory of the currently running script
BDOTDIR="${BDOTDIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# Export BDOTDIR
export BDOTDIR

# Function to load files from a directory
# Parameters:
#   $1: Directory path
#   $2: File extension (default is "bash")
init_config() {
  for conf in $(find $1 -type f); do
    if [ -r "$conf" ]; then
      # echo "$conf"
      # time . "$conf"
      . "$conf"
    else
      printf "File not readable:  %s" "$conf"
    fi
  done
}

# Load resources and functions
init_config "$BDOTDIR/resources"
# init_config "$BDOTDIR/functions"
