#! /bin/sh
# shellcheck disable=SC2034,SC2154

# @___________________________________________________ CACHE & CONF<|

case "$sys_INFO" in
*Windows*)
  DATA_HOME="$HOME/AppData/Roaming" # powershell \$env:APPDATA
  CACHE_HOME="$HOME/AppData/Local"  # powershell \$env:LOCALAPPDATA
  CONFIG_HOME="$HOME/.config"
  ;;
*)
  DATA_HOME="${XDG_DATA_HOME:-"$HOME/.local/share"}"
  CACHE_HOME="${XDG_CACHE_HOME:-"$HOME/.cache"}"
  CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
  STATE_HOME="${XDG_STATE_HOME:-"$HOME/.local/state"}"
  RUNTIME_DIR="${XDG_RUNTIME_DIR:-"/run/user/$id -u)"}"
  TRASH="${DATA_HOME}/Trash/files"
  ;;
esac

XDG_DATA_HOME="$DATA_HOME"
XDG_CACHE_HOME="$CACHE_HOME"
XDG_CONFIG_HOME="$CONFIG_HOME"
[ "$STATE_HOME" ] && XDG_STATE_HOME="$STATE_HOME"
[ "$RUNTIME_DIR" ] && XDG_RUNTIME_DIR="$RUNTIME_DIR"
