#! /bin/sh
# shellcheck disable=SC2034,SC2154

BDOTDIR="$DOTS_CLI/bash"
ZDOTDIR="$DOTS_CLI/zsh"
DDOTDIR="$DOTS_CLI/dash"
FDOTDIR="$DOTS_CLI/fish"
NDOTDIR="$DOTS_CLI/nushell"
GDOTDIR="$DOTS_CLI/git"
PDOTDIR="$DOTS_CLI/pwsh"
SSHDIR="$HOME/.ssh"

# | Config Files
RC_bash_home="$HOME/.bashrc"
RC_bash="$BDOTDIR/config"
RC_dash="$DDOTDIR/.config"
RC_zsh="$ZDOTDIR/.config"
RC_fish="$FDOTDIR/.config"
RC_nush="$NDOTDIR/.config"
RC_git="$GDOTDIR/global/config"
RC_pwsh="$PDOTDIR/config/pshrc.ps1"
RC_ssh="$SSHDIR/config"
RC_init="$DOTS/.dotsrc"
