#!/bin/sh

: <<'Parameter_Expansion'
  # https://stackoverflow.com/questions/4168371/how-can-i-remove-all-text-after-a-character-in-bash

  a='hello:world'

  b=${a%:*}
  echo "$b"
  hello

  a='hello:world:of:tomorrow'

  echo "${a%:*}"
  hello:world:of

  echo "${a%%:*}"
  hello

  echo "${a#*:}"
  world:of:tomorrow

  echo "${a##*:}"
  tomorrow

}
Parameter_Expansion
