#!/bin/sh
# TODO: Handle this declaritivly via the flake

#@ Enable messaging
VERBOSE=true

{ #/> NixOS Flake <\#

    #@ Set flake root directory
    NixOS_FLAKE="${NixOS_FLAKE:-/etc/nixos}"

    #@ Make the variable available
    export NixOS_FLAKE

}

{ #/> Scripts <\#

    #@ Set flake scripts directory
    NixOS_SCRIPTS="$NixOS_FLAKE/Global/Scripts"

    #@ Make scripts executable
    find "$NixOS_SCRIPTS" \
        -type f ! \
        -perm -u=x \
        -exec doas chmod u+x {} \;

    #@ Make the scripts available
    export PATH="$PATH:$NixOS_SCRIPTS"
}

{ #/> Environment <\#

    #@ Set flake environment directory
    NixOS_ENV="$NixOS_FLAKE/Global/Environment"

    #@ Initialize Flake environment variables and aliases
    for env in "$NixOS_ENV"/*; do
        if [ -f "$env" ] && [ "$(basename "$env")" != "profile" ]; then
            . "$env"
        fi
    done

}

{ #/> DOTS <\#

    #@ Set DOTS directory
    DOTS="$NixOS_FLAKE/Admin/Other"

    #@ Initialize DOTS
    [ -f "$DOTS/.dotsrc" ] && . "$DOTS/.dotsrc"

}

#@ Print success message
[ -n "${VERBOSE}" ] && printf "NixOS_FLAKE=[%s]\n" "${NixOS_FLAKE}"
