
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[line_break]
# disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Dotfiles" = "°°°"
"~/DOTS" = "°°°"

[package]
disabled = true

[cmd_duration]
min_time = 1000
show_notifications = true

[time]
disabled = false
format = '🕙[ $time ]($style)'
time_format = "%H:%M"
utc_time_offset = "-5"
time_range = '22:00:00-07:00:00'

[shell]
disabled = true

[status]
disabled = false
symbol = "🔴"
format = '[$symbol $common_meaning$signal_name$maybe_int]($style) '
map_symbol = true

[character]
success_symbol = "🚀"
error_symbol = "🚩"

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[sudo]
style = "bold green"
symbol = "👩‍💻 "
allow_windows = true
disabled = false

[git_status]
# disabled = true
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"
