# theme = "catppuccin_mocha"
# theme = "noctis_bordo"
# theme = "noctis"
# theme = "kanagawa"
# theme = "tokyonight_storm"
# theme = "monokai_pro_machine"
# theme = "monokai_pro_octagon"
# theme = "monokai_pro_spectrum"
# theme = "monokai_pro_ristretto"
# theme = "rose_pine_moon"
theme = "monokai_pro_spectrum"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
# auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.file-picker]
# hidden = false

[editor.statusline]
# left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w" # Maps the Ctrl-s to the typable command :w which is an alias for :write (save file)
C-S-o = ":config-open" # Maps the Ctrl-o to opening of the helix config file
C-S-r = ":config-reload" # Maps the Ctrl-o to opening of the helix config file
a = "move_char_left" # Maps the 'a' key to the move_char_left command
w = "move_line_up" # Maps the 'w' key move_line_up
"C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = [
  "open_below",
  "normal_mode",
] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
