#!/bin/sh

# This script sets and executes the terminal emulator.
# The terminal emulator is set to the last available terminal emulator in the list.

type alacritty > /dev/null 2>&1 && terminal="alacritty"
type kitty > /dev/null 2>&1 && terminal="kitty"
type rio > /dev/null 2>&1 && terminal="rio"
type     wezterm > /dev/null 2>&1 && terminal="wezterm cli spawn"

$terminal "$@"
