[toolchain]
channel = "nightly-2023-03-30"
components = ["rust-src", "llvm-tools-preview"]
targets = [
  "wasm32-unknown-unknown",
  # "x86_64-unknown-linux-musl",
  # "x86_64-unknown-linux-gnu",
  # "aarch64-unknown-linux-musl",
]
profile = "default"
