#!/bin/sh

#@ List packages to check and install
packages="${*:-"helix git"}"
installed_packages=""
count=0

#@ Loop through each package
for package in $packages; do

  #@ Check if the package is installed
  if ! nix-env --query "$package" >/dev/null 2>&1; then

    #@ Install the package
    nix-env \
      --file '<nixpkgs>' \
      --install --attr "$package" \
      >/dev/null 2>&1
    if [ "${count}" -eq 0 ]; then
      installed_packages="${package}"
    else
      installed_packages="${installed_packages}, ${package}"
    fi
    count=$((count + 1))
  fi
done

#@ Print the installed packages if any
if [ "${count}" -gt 0 ]; then
  if [ "${count}" -gt 1 ]; then
    last_package=$(
      printf "%s\n" "${installed_packages}" |
        awk -F', ' '{print $NF}'
    )
    installed_packages=$(
      printf "%s\n" "${installed_packages}" |
        sed "s/, ${last_package}$/, and ${last_package}/"
    )
  fi
  # printf "     Installed |>  %s\n" "${installed_packages}"
fi
