#!/bin/sh

#@ Declare the environment variables
[ -d "$DOTS" ] || {
  printf "DOTS directory missing"
  exit 1
}
[ "$NIXS" ] || {
  printf "NIXS variable unset"
  exit 1
}
# OLD_DIR="$(pwd)"

# #@ Go to the dotfiles directory
# cd "$DOTS" || exit 1

#@ Get the updates
dots reset --hard
dots pull

#@ Make scripts executable
find "$NIXS" \
  -type f ! \
  -perm -u=x \
  -exec chmod u+x {} \;

# #@ Return to the original directory
# cd "$OLD_DIR" || exit 1
