#!/bin/sh

#@ Declare the environment variables
[ -d "$DOTS" ] || {
  printf "DOTS directory missing"
  exit 1
}
[ "$NIXS" ] || {
  printf "NIXS variable unset"
  exit 1
}

#@ Delete the dotfiles
rm -rf "$DOTS"

#@ Clone the dotfiles repository
git clone https://github.com/craole-cc/dotfiles.git "$DOTS"

#@ Make scripts executable
find "$NIXS" \
  -type f ! \
  -perm -u=x \
  -exec chmod u+x {} \;
