#!/bin/sh

#| Initialize NixOS Flake Scripts
NixOS_FLAKE="/etc/nixos"
NixOS_SCRIPTS="$NixOS_FLAKE/Scripts"

#| Make scripts executable
find "$NixOS_SCRIPTS" \
    -type f ! \
    -perm -u=x \
    -exec doas chmod u+x {} \;

#| Make the scripts available
PATH="$PATH:$NixOS_SCRIPTS"

#| Initialize the variables and scripts
printf "Welcome to NixOS\n"
export NixOS_FLAKE NixOS_SCRIPTS PATH
alias nosR='doas NixOS-rebuild'
alias nosR_trace='doas NixOS-rebuild --show-trace'
alias nosC='doas NixOS-check'
alias nosC_trace='nosC --show-trace'