#!/bin/sh

#| Initialize NixOS Flake Scripts
NixOS_FLAKE="/etc/nixos"
NixOS_SCRIPTS="$NixOS_FLAKE/Scripts"

#| Make scripts executable
find "$NixOS_SCRIPTS" \
    -type f ! \
    -perm -u=x \
    -exec doas chmod u+x {} \;

#| Make the scripts available
PATH="$PATH:$NixOS_SCRIPTS"

#| Initialize the variables and scripts
export NixOS_FLAKE NixOS_SCRIPTS PATH