#!/bin/sh

NixOS_FLAKE="${NixOS_FLAKE:-/etc/nixos}"

if cd "${NixOS_FLAKE}" ;then

    printf "%s %s\n" "Rebuilding NixOS Flake at" "${NixOS_FLAKE}"

    #/> Git Update 
    git add . && git commit -m "${@:-"General updates"}"

    #/> Flake Update 
    nix flake update

    #/> Flake Rebuild
    nixos-rebuild switch

else
    
    printf "%s\n" "Failed to access" "${NixOS_FLAKE}"
    exit 1

fi