#!/bin/sh

#@ Print appropriate error message
case "${1}" in
--*)
  msg="$(printf ":::%s:::" "${1#--}" | tr '[:lower:]' '[:upper:]')"
  var=${2}
  shift 2
  arg=${*}
  ;;
*)
  shift
  printf "A valid %s is required" "${*}"
  ;;
esac

if
  [ -n "${msg}" ] && [ -n "${var}" ] && [ -z "${arg}" ]
then
  printf "%s %s" "${msg}" "${var}"
elif
  [ -n "${msg}" ] && [ -n "${var}" ] && [ -n "${arg}" ]
then
  printf "%s %s -> %s" "${msg}" "${var}" "${arg}"
else
  printf "%s" "${*}"
fi
