#!/bin/sh
get_updated_dots
# nix-env --uninstall jq parted bat helix hello cowsay

#@ List packages to check and install
packages="git parted bat helix"
installed_packages="$(get_deps "$packages")"

[ "$installed_packages" ] &&
  printf "     Installed |>  %s\n" "${installed_packages}"
