#!/bin/sh

label="Git Reposiory URL"
value="$1"

#@ Exit early if info missing
[ "$value" ] || {
  pout --missing "$label"
  exit 1
}

if git ls-remote "$value" -q >/dev/null 2>&1; then
  #@ Update/Return Variable
  printf "%s" "$value"
else
  pout --invalid "$label" "${value}"
  exit 1
fi
