#!/bin/sh

label="Git Reposiory URL"
value="$1"
regex="^\(https?\|git\)://.*\.git$"

#@ Exit early if info missing
[ "$value" ] || {
  pout --missing "$label"
  exit 1
}

#@ Use a regular expression to validate the git email address
validate_with_regex "$value" "$regex"
#  {
#   pout --invalid "$label" "${value}"
#   exit 1
# }

#@ Update/Return Variable
printf "%s" "$value"
