#!/bin/sh

label="Email"
value="$1"
regex="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

#@ Exit early if info missing
[ "$value" ] || {
  pout --missing "$label"
  exit 1
}

#@ Use a regular expression to validate the git email address
if printf '%s' "$value" | grep -Eq "$regex"; then
  #@ Update/Return Variable
  printf "%s" "$value"
else
  pout --invalid "$label" "${value}"
  exit 1
fi
