#!/bin/sh

deploy_symlink() {
  ln "${1}" "${2}" \
    --symbolic \
    --force \
    --verbose
}

# res_HOME="/home/craole/DOTS/Admin/Other/Resources/Home"

res_HOME="${DOTS:-/home/craole/DOTS/Admin/Other}/Resources/Home"

deploy_symlink "${res_HOME}"/profile "${HOME}"/.profile
deploy_symlink "${res_HOME}"/bashrc "${HOME}"/.bashrc
