#!/bin/sh

NixOS_FLAKE="${NixOS_FLAKE:-/etc/nixos}"
message="General flake updates"
trace=0

{ #/> Options
    while [ "$#" -ge 1 ]; do
        case $1 in
        -t | --show-trace) trace=1 ;;
        *) message="$*" ;;
        esac
        shift
    done
}

{ #/> Access Flake Root
    if cd "${NixOS_FLAKE}"; then
        printf "%s %s\n" "Checking the NixOS Flake at" "${NixOS_FLAKE}"
    else

        printf "%s\n" "Failed to access" "${NixOS_FLAKE}"
        exit 1
    fi
}

{ #/> Flake Check
    if [ "$trace" -eq 1 ]; then
        nix flake check --show-trace
    else
        nix flake check
    fi
}
