SCGI_URL = "/run/rtorrent/rpc.sock"
RTORRENT_RC = ""
CONFIG_PY = "~/.config/pyrosimple/config.py"
CONFIG_PY_LOADED = false
SORT_FIELDS = "name,hash"
FAST_QUERY = 0
ITEM_CACHE_EXPIRATION = 5.0
SAFETY_CHECKS_ENABLED = true
MKTOR_IGNORE = [
    "core",
    "CVS",
    ".*",
    "*~",
    "*.swp",
    "*.tmp",
    "*.bak",
    "[Tt]humbs.db",
    "[Dd]esktop.ini",
    "ehthumbs_vista.db",
]

[ALIASES]

[ALIAS_TRAITS]

[CONNECTIONS]

[FORMATS]
default = "{{d.name}} 	[{{d.alias}}]\n  {{d.is_private|fmt(\"is_private\")}} {{d.is_open|fmt(\"is_open\")}} {{d.is_active|fmt(\"is_active\")}} P{{d.prio|int}} {%if d.is_complete %}     done{%else%}{{\"%8.2f\"|format(d.done)}}%{%endif%}	{{d.size|sz}} U:{{d.up|sz}}/s  D:{{d.down|sz}}/s T:{{d.throttle|fmt(\"throttle\")}}"
short = "{%set ESC = \"\u001b\" %}{%if d.down > 0%}{{ESC+\"[1m\"}}{%endif%}{%if d.is_open%}O{%else%} {%endif%}{%if  d.is_active%}A{%else%} {%endif%}{%if not d.is_complete%}{{ESC+\"[36m\"}}{{ \"{:>3}\".format(d.done | round | int) }}{{ESC+\"[0m\"}}{%else%}  D{%endif%} {{\"{:>10}\".format(d.size | filesizeformat(True))}} {%if d.message%}{{ESC+\"[31m\"}}{%endif%} {{d.alias.rjust(3)}}{{ESC+\"[0m\"}} {%if d.down > 0%}{{ESC+\"[1m\"}}{%endif%}{{d.name}}{{ESC+\"[0m\"}}"
filelist = "{% for f in d.files %}{{d.realpath}}{% if d.is_multi_file %}/{{f.path}}{% endif %}{% if loop.index != loop.length %}\n{% endif %}{% endfor %}"
action = "{{now()|iso}} {{action}}	 {{d.name}} [{{d.alias}}]"
