use-grammars = { only = [
  "rust",
  "html",
  "css",
  "sql",
  "python",
  "bash",
  "make",
  "toml",
  "json",
  "json5",
  "yaml",
  "markdown",
  "awk",
  "nu",
  "nix",
] }

[[languages]]
name = "rust"